[build]
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["mysql2", "sequelize"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

